export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS'
export const CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER = 'USER_REGISTER'

export const SHOP_LOGIN_SUCCESS = 'SHOP_LOGIN_SUCCESS'
export const SHOP_LOGIN_FAILED = 'SHOP_LOGIN_FAILED'

export const INITIALIZE_CART = 'INITIALIZE_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART'
export const UPDATE_QUANTITY_SUCCESS = 'UPDATE_QUANTITY_SUCCESS'
export const UPDATE_QUANTITY_FAILED = 'UPDATE_QUANTITY_FAILED'
export const CHOOSE_CART_ITEM = 'CHOOSE_CART_ITEM'
export const UN_CHOOSE_CART_ITEM = 'UN_CHOOSE_CART_ITEM'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'


