const cart = {
    INITIALIZE_CART: 'INITIALIZE_CART',
    LOAD_CART: 'LOAD_CART',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    UPDATE_QUANTITY: 'UPDATE_QUANTITY',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    SELECT_ITEM: 'SELECT_ITEM',
    UN_SELECT_ITEM: 'UN_SELECT_ITEM',
}
export default cart;

