const user = {
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    CHECK_TOKEN_SUCCESS: 'CHECK_TOKEN_SUCCESS',
    CHECK_TOKEN_FAILED: 'CHECK_TOKEN_FAILED',
    USER_LOGOUT: 'USER_LOGOUT',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',
    USER_REGISTER: 'USER_REGISTER',
}
export default user;